<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.RWA3FG5.Symfony\Component\Validator\ConstraintViolationListInterface' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.RWA3FG5": it references interface "Symfony\\Component\\Validator\\ConstraintViolationListInterface" but no such service exists. Did you create a class that implements this interface?');
