<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\ArticlesController' shared autowired service.

return $this->services['App\Controller\ArticlesController'] = new \App\Controller\ArticlesController(($this->privates['App\Repository\ArticleRepository'] ?? $this->load('getArticleRepositoryService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')));
