<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Security\TokenAuthenticator' shared autowired service.

return $this->privates['App\Security\TokenAuthenticator'] = new \App\Security\TokenAuthenticator();
