<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Faker\Generator' shared service.

$this->services['Faker\Generator'] = $instance = \Faker\Factory::create('en_US');

$instance->seed(1);
$instance->addProvider(($this->privates['nelmio_alice.faker.provider.alice'] ?? $this->privates['nelmio_alice.faker.provider.alice'] = new \Nelmio\Alice\Faker\Provider\AliceProvider()));

return $instance;
