<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hautelook_alice.alice.generator.instantiator.chainable.instantiated_reference_instantiator' shared service.

$this->privates['hautelook_alice.alice.generator.instantiator.chainable.instantiated_reference_instantiator'] = $instance = new \Hautelook\AliceBundle\Alice\Generator\Instantiator\Chainable\InstantiatedReferenceInstantiator();

$instance->setContainer($this);

return $instance;
