<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hautelook_alice.alice.file_locator.kernel' shared service.

return $this->privates['hautelook_alice.alice.file_locator.kernel'] = new \Hautelook\AliceBundle\Alice\FileLocator\KernelFileLocator(($this->privates['nelmio_alice.file_locator.default'] ?? $this->privates['nelmio_alice.file_locator.default'] = new \Nelmio\Alice\FileLocator\DefaultFileLocator()), ($this->services['kernel'] ?? $this->get('kernel', 1)));
