<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.resolver.parameter.registry' shared service.

return $this->privates['nelmio_alice.generator.resolver.parameter.registry'] = new \Nelmio\Alice\Generator\Resolver\Parameter\ParameterResolverRegistry(array(0 => ($this->privates['nelmio_alice.generator.resolver.parameter.chainable.static_parameter_resolver'] ?? $this->privates['nelmio_alice.generator.resolver.parameter.chainable.static_parameter_resolver'] = new \Nelmio\Alice\Generator\Resolver\Parameter\Chainable\StaticParameterResolver()), 1 => ($this->privates['nelmio_alice.generator.resolver.parameter.chainable.array_parameter_resolver'] ?? $this->privates['nelmio_alice.generator.resolver.parameter.chainable.array_parameter_resolver'] = new \Nelmio\Alice\Generator\Resolver\Parameter\Chainable\ArrayParameterResolver()), 2 => ($this->privates['nelmio_alice.generator.resolver.parameter.chainable.recursive_parameter_resolver'] ?? $this->load('getNelmioAlice_Generator_Resolver_Parameter_Chainable_RecursiveParameterResolverService.php'))));
