<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.resolver.value.chainable.fixture_property_reference_resolver' shared service.

return $this->privates['nelmio_alice.generator.resolver.value.chainable.fixture_property_reference_resolver'] = new \Nelmio\Alice\Generator\Resolver\Value\Chainable\FixturePropertyReferenceResolver(($this->privates['nelmio_alice.property_accessor.std'] ?? $this->load('getNelmioAlice_PropertyAccessor_StdService.php')));
