<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.instantiator.existing_instance' shared service.

return $this->privates['nelmio_alice.generator.instantiator.existing_instance'] = new \Nelmio\Alice\Generator\Instantiator\ExistingInstanceInstantiator(($this->privates['nelmio_alice.generator.instantiator.resolver'] ?? $this->load('getNelmioAlice_Generator_Instantiator_ResolverService.php')));
