<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.resolver.fixture_set.simple' shared service.

return $this->privates['nelmio_alice.generator.resolver.fixture_set.simple'] = new \Nelmio\Alice\Generator\Resolver\FixtureSet\SimpleFixtureSetResolver(($this->privates['nelmio_alice.generator.resolver.parameter_bag.remove_conflicting_parameters'] ?? $this->load('getNelmioAlice_Generator_Resolver_ParameterBag_RemoveConflictingParametersService.php')), ($this->privates['nelmio_alice.generator.resolver.fixture_bag.template_bag'] ?? $this->privates['nelmio_alice.generator.resolver.fixture_bag.template_bag'] = new \Nelmio\Alice\Generator\Resolver\Fixture\TemplateFixtureBagResolver()));
