<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.fixture_builder.denormalizer.fixture.specs.value.simple_value_denormalizer' shared service.

return $this->privates['nelmio_alice.fixture_builder.denormalizer.fixture.specs.value.simple_value_denormalizer'] = new \Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\SpecificationBagDenormalizer\Value\SimpleValueDenormalizer(($this->privates['nelmio_alice.fixture_builder.expression_language.parser.function_fixture_reference_parser'] ?? $this->load('getNelmioAlice_FixtureBuilder_ExpressionLanguage_Parser_FunctionFixtureReferenceParserService.php')));
