<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.fixture_builder.simple' shared service.

return $this->privates['nelmio_alice.fixture_builder.simple'] = new \Nelmio\Alice\FixtureBuilder\SimpleBuilder(($this->privates['nelmio_alice.fixture_builder.denormalizer.simple'] ?? $this->load('getNelmioAlice_FixtureBuilder_Denormalizer_SimpleService.php')));
