<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.fixture_builder.denormalizer.simple' shared service.

return $this->privates['nelmio_alice.fixture_builder.denormalizer.simple'] = new \Nelmio\Alice\FixtureBuilder\Denormalizer\SimpleDenormalizer(($this->privates['nelmio_alice.fixture_builder.denormalizer.parameter.simple_parameter_bag_denormalizer'] ?? $this->privates['nelmio_alice.fixture_builder.denormalizer.parameter.simple_parameter_bag_denormalizer'] = new \Nelmio\Alice\FixtureBuilder\Denormalizer\Parameter\SimpleParameterBagDenormalizer()), ($this->privates['nelmio_alice.fixture_builder.denormalizer.fixture.simple_fixture_bag_denormalizer'] ?? $this->load('getNelmioAlice_FixtureBuilder_Denormalizer_Fixture_SimpleFixtureBagDenormalizerService.php')));
