<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.fixture_builder.expression_language.parser.string_parser' shared service.

return $this->privates['nelmio_alice.fixture_builder.expression_language.parser.string_parser'] = new \Nelmio\Alice\FixtureBuilder\ExpressionLanguage\Parser\StringMergerParser(($this->privates['nelmio_alice.fixture_builder.expression_language.parser.simple_parser'] ?? $this->load('getNelmioAlice_FixtureBuilder_ExpressionLanguage_Parser_SimpleParserService.php')));
