<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.fixture_builder.denormalizer.fixture.simple_fixture_bag_denormalizer' shared service.

return $this->privates['nelmio_alice.fixture_builder.denormalizer.fixture.simple_fixture_bag_denormalizer'] = new \Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\SimpleFixtureBagDenormalizer(($this->privates['nelmio_alice.fixture_builder.denormalizer.fixture.registry_denormalizer'] ?? $this->load('getNelmioAlice_FixtureBuilder_Denormalizer_Fixture_RegistryDenormalizerService.php')), ($this->privates['nelmio_alice.fixture_builder.denormalizer.flag_parser.element'] ?? $this->load('getNelmioAlice_FixtureBuilder_Denormalizer_FlagParser_ElementService.php')));
