<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.caller.registry' shared service.

return $this->privates['nelmio_alice.generator.caller.registry'] = new \Nelmio\Alice\Generator\Caller\CallProcessorRegistry(array(0 => ($this->privates['nelmio_alice.generator.caller.chainable.configurator_method_call'] ?? $this->privates['nelmio_alice.generator.caller.chainable.configurator_method_call'] = new \Nelmio\Alice\Generator\Caller\Chainable\ConfiguratorMethodCallProcessor()), 1 => ($this->privates['nelmio_alice.generator.caller.chainable.method_call_with_reference'] ?? $this->privates['nelmio_alice.generator.caller.chainable.method_call_with_reference'] = new \Nelmio\Alice\Generator\Caller\Chainable\MethodCallWithReferenceProcessor()), 2 => ($this->privates['nelmio_alice.generator.caller.chainable.optional_method_call'] ?? $this->privates['nelmio_alice.generator.caller.chainable.optional_method_call'] = new \Nelmio\Alice\Generator\Caller\Chainable\OptionalMethodCallProcessor()), 3 => ($this->privates['nelmio_alice.generator.caller.chainable.simple_call'] ?? $this->privates['nelmio_alice.generator.caller.chainable.simple_call'] = new \Nelmio\Alice\Generator\Caller\Chainable\SimpleMethodCallProcessor())));
