<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.file_parser.runtime_cache' shared service.

return $this->privates['nelmio_alice.file_parser.runtime_cache'] = new \Nelmio\Alice\Parser\RuntimeCacheParser(($this->privates['nelmio_alice.file_parser.registry'] ?? $this->load('getNelmioAlice_FileParser_RegistryService.php')), ($this->privates['hautelook_alice.alice.file_locator.kernel'] ?? $this->load('getHautelookAlice_Alice_FileLocator_KernelService.php')), ($this->privates['nelmio_alice.file_parser.default_include_processor'] ?? $this->load('getNelmioAlice_FileParser_DefaultIncludeProcessorService.php')));
