<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.resolver.fixture_set.remove_conflicting_objects' shared service.

return $this->privates['nelmio_alice.generator.resolver.fixture_set.remove_conflicting_objects'] = new \Nelmio\Alice\Generator\Resolver\FixtureSet\RemoveConflictingObjectsResolver(($this->privates['nelmio_alice.generator.resolver.fixture_set.simple'] ?? $this->load('getNelmioAlice_Generator_Resolver_FixtureSet_SimpleService.php')));
