<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.fixture_builder.denormalizer.fixture.chainable.simple_range' shared service.

return $this->privates['nelmio_alice.fixture_builder.denormalizer.fixture.chainable.simple_range'] = new \Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\Chainable\SimpleCollectionDenormalizer(($this->privates['nelmio_alice.fixture_builder.denormalizer.fixture.chainable.temporary_range'] ?? $this->load('getNelmioAlice_FixtureBuilder_Denormalizer_Fixture_Chainable_TemporaryRangeService.php')));
