<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.resolver.parameter_bag.remove_conflicting_parameters' shared service.

return $this->privates['nelmio_alice.generator.resolver.parameter_bag.remove_conflicting_parameters'] = new \Nelmio\Alice\Generator\Resolver\Parameter\RemoveConflictingParametersParameterBagResolver(($this->privates['nelmio_alice.generator.resolver.parameter_bag.simple'] ?? $this->load('getNelmioAlice_Generator_Resolver_ParameterBag_SimpleService.php')));
