<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.hydrator.property.symfony_property_access' shared service.

return $this->privates['nelmio_alice.generator.hydrator.property.symfony_property_access'] = new \Nelmio\Alice\Generator\Hydrator\Property\SymfonyPropertyAccessorHydrator(($this->privates['nelmio_alice.property_accessor.std'] ?? $this->load('getNelmioAlice_PropertyAccessor_StdService.php')));
