<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTpGYZIc\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTpGYZIc/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTpGYZIc.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTpGYZIc\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerTpGYZIc\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'TpGYZIc',
    'container.build_id' => '2fdb06c1',
    'container.build_time' => 1534835932,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTpGYZIc');
