<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPAJsJ31\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPAJsJ31/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPAJsJ31.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPAJsJ31\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerPAJsJ31\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'PAJsJ31',
    'container.build_id' => '81225c2e',
    'container.build_time' => 1535013876,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPAJsJ31');
