<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWed7Wd1\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWed7Wd1/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWed7Wd1.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWed7Wd1\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerWed7Wd1\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Wed7Wd1',
    'container.build_id' => '0bd581af',
    'container.build_time' => 1534865245,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWed7Wd1');
